micronaut:
  application:
    name: todo
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    entity-scan:
        packages: 'todo.svc.todo'
    properties:
        hibernate:
            hbm2ddl:
                auto: create
            show_sql: true
            id:
                new_generator_mappings: true
